// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Audio$Gayer from "./Audio.bs.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as Json_encode from "@glennsl/bs-json/src/Json_encode.bs.js";
import * as Canvas$Gayer from "./Canvas.bs.js";

function analysisOptions(json) {
  return /* record */[
          /* input */Json_decode.field("input", Audio$Gayer.AudioInput[/* DecodeAudioInput */1][/* audioInputSetting */0], json),
          /* destRect */Json_decode.field("destRect", Canvas$Gayer.DrawCommand[/* DecodeDrawCommand */2][/* rect */2], json)
        ];
}

var DecodeAnalysisOptions = /* module */[/* analysisOptions */analysisOptions];

function analysisOptions$1(r) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "input",
                Curry._1(Audio$Gayer.AudioInput[/* EncodeAudioInput */0][/* audioInputSetting */0], r[/* input */0])
              ],
              /* :: */[
                /* tuple */[
                  "destRect",
                  Curry._1(Canvas$Gayer.DrawCommand[/* EncodeDrawCommand */1][/* rect */2], r[/* destRect */1])
                ],
                /* [] */0
              ]
            ]);
}

var EncodeAnalysisOptions = /* module */[/* analysisOptions */analysisOptions$1];

var defaultAnalysisOptions = /* record */[
  /* input : Mic */2,
  /* destRect : record */[
    /* x : Add */Block.__(5, [
        /* Width */0,
        /* Pixels */Block.__(2, [-1])
      ]),
    /* y : Pixels */Block.__(2, [0]),
    /* w : Pixels */Block.__(2, [1]),
    /* h : Height */1
  ]
];

export {
  defaultAnalysisOptions ,
  DecodeAnalysisOptions ,
  EncodeAnalysisOptions ,
  
}
/* Audio-Gayer Not a pure module */
