// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_int32 from "bs-platform/lib/es6/caml_int32.js";
import * as Audio$Gayer from "./Audio.bs.js";
import * as Music$Gayer from "./Music.bs.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Video$Gayer from "./Video.bs.js";
import * as Canvas$Gayer from "./Canvas.bs.js";

function setCanvasRef(theRef, param) {
  param[/* state */1][/* canvasRef */9][0] = (theRef == null) ? /* None */0 : [theRef];
  return /* () */0;
}

var component = ReasonReact.reducerComponent("App");

function maybeUpdateCanvas(maybeEl, f) {
  var match = maybeEl[0];
  if (match) {
    return Curry._1(f, match[0]);
  } else {
    return /* () */0;
  }
}

function maybeMapFilterBank(f, maybeFilterBank) {
  if (maybeFilterBank) {
    return Curry._1(f, maybeFilterBank[0]);
  } else {
    return /* () */0;
  }
}

function clearCanvas(canvasElement, width, height) {
  var ctx = canvasElement.getContext("2d");
  ctx.clearRect(0, 0, width, height);
  return /* () */0;
}

function drawCanvas(canvasElement, width, height, xIndex, channelToRead, maybeVisualInput) {
  var ctx = canvasElement.getContext("2d");
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, width, height);
  if (maybeVisualInput) {
    ctx.drawImage(maybeVisualInput[0], 0, 0, width, height);
  }
  var slice = ctx.getImageData(xIndex, 0, 1, height);
  var values = Canvas$Gayer.imageDataToFloatArray(slice, channelToRead);
  ctx.strokeStyle = "white";
  Canvas$Gayer.Ctx[/* line */4](ctx, /* tuple */[
        xIndex,
        0
      ], /* tuple */[
        xIndex,
        height
      ]);
  return values;
}

function make($staropt$star, $staropt$star$1, _) {
  var width = $staropt$star ? $staropt$star[0] : 640;
  var height = $staropt$star$1 ? $staropt$star$1[0] : 120;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var filterBank = Audio$Gayer.defaultFilterBank(/* Some */[Audio$Gayer.defaultAudioCtx], /* Some */[height], /* Some */[Audio$Gayer.defaultQ]);
              Audio$Gayer.connectFilterBank(self[/* state */1][/* filterInput */4], filterBank);
              Video$Gayer.turnOnVideo(/* () */0).then((function (video) {
                      Curry._1(self[/* send */3], /* SetVisualInput */Block.__(1, [video]));
                      return Promise.resolve(/* () */0);
                    }));
              Curry._1(self[/* send */3], /* SetFilterBank */Block.__(2, [filterBank]));
              Curry._1(self[/* send */3], /* Clear */0);
              self[/* state */1][/* timerId */10][0] = /* Some */[setInterval((function () {
                        return Curry._1(self[/* send */3], /* Tick */1);
                      }), 300)];
              Audio$Gayer.getAudioSource(Audio$Gayer.defaultAudioCtx).then((function (maybeSource) {
                      if (maybeSource) {
                        Curry._1(self[/* send */3], /* SetFilterInput */Block.__(0, [maybeSource[0]]));
                      }
                      return Promise.resolve(/* () */0);
                    }));
              return /* () */0;
            }),
          /* didUpdate */(function (param) {
              var newSelf = param[/* newSelf */1];
              var oldSelf = param[/* oldSelf */0];
              if (oldSelf[/* state */1][/* filterInput */4] !== newSelf[/* state */1][/* filterInput */4]) {
                var partial_arg = oldSelf[/* state */1][/* filterInput */4];
                maybeMapFilterBank((function (param) {
                        return Audio$Gayer.disconnectFilterBank(partial_arg, param);
                      }), oldSelf[/* state */1][/* filterBank */8]);
              }
              if (oldSelf[/* state */1][/* filterBank */8] !== newSelf[/* state */1][/* filterBank */8]) {
                var partial_arg$1 = oldSelf[/* state */1][/* filterInput */4];
                return maybeMapFilterBank((function (param) {
                              return Audio$Gayer.disconnectFilterBank(partial_arg$1, param);
                            }), oldSelf[/* state */1][/* filterBank */8]);
              } else {
                return 0;
              }
            }),
          /* willUnmount */(function (self) {
              var partial_arg = self[/* state */1][/* filterInput */4];
              return maybeMapFilterBank((function (param) {
                            return Audio$Gayer.disconnectFilterBank(partial_arg, param);
                          }), self[/* state */1][/* filterBank */8]);
            }),
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          onClick: (function () {
                              return Curry._1(self[/* send */3], /* Tick */1);
                            })
                        }, React.createElement("h1", undefined, "GAYER"), React.createElement("canvas", {
                              ref: Curry._1(self[/* handle */0], setCanvasRef),
                              height: height.toString(),
                              width: width.toString()
                            }));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* xIndex */0,
                      /* xDelta */1,
                      /* inputGain */1.0,
                      /* outputGain */0.05,
                      /* filterInput */Audio$Gayer.defaultNoise,
                      /* visualInput : None */0,
                      /* channelToRead : A */3,
                      /* allowedPitchClasses */Curry._1(Music$Gayer.PitchSet[/* of_list */25], /* :: */[
                            0,
                            /* :: */[
                              2,
                              /* :: */[
                                5,
                                /* :: */[
                                  7,
                                  /* :: */[
                                    9,
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]),
                      /* filterBank : None */0,
                      /* canvasRef */[/* None */0],
                      /* timerId */[/* None */0]
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action === 0) {
                  return /* SideEffects */Block.__(1, [(function (self) {
                                return maybeUpdateCanvas(self[/* state */1][/* canvasRef */9], (function (canvas) {
                                              return clearCanvas(canvas, width, height);
                                            }));
                              })]);
                } else {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            /* record */[
                              /* xIndex */Caml_int32.mod_(state[/* xIndex */0] + state[/* xDelta */1] | 0, width),
                              /* xDelta */state[/* xDelta */1],
                              /* inputGain */state[/* inputGain */2],
                              /* outputGain */state[/* outputGain */3],
                              /* filterInput */state[/* filterInput */4],
                              /* visualInput */state[/* visualInput */5],
                              /* channelToRead */state[/* channelToRead */6],
                              /* allowedPitchClasses */state[/* allowedPitchClasses */7],
                              /* filterBank */state[/* filterBank */8],
                              /* canvasRef */state[/* canvasRef */9],
                              /* timerId */state[/* timerId */10]
                            ],
                            (function (self) {
                                return maybeUpdateCanvas(self[/* state */1][/* canvasRef */9], (function (canvas) {
                                              var rawFilterValues = drawCanvas(canvas, width, height, self[/* state */1][/* xIndex */0], self[/* state */1][/* channelToRead */6], self[/* state */1][/* visualInput */5]);
                                              var filterValues = Music$Gayer.filterByPitchSet(self[/* state */1][/* allowedPitchClasses */7], rawFilterValues);
                                              return maybeMapFilterBank((function (filterBank) {
                                                            return Audio$Gayer.updateFilterBank(filterBank, filterValues, self[/* state */1][/* inputGain */2], self[/* state */1][/* outputGain */3]);
                                                          }), self[/* state */1][/* filterBank */8]);
                                            }));
                              })
                          ]);
                }
              } else {
                switch (action.tag | 0) {
                  case 0 : 
                      return /* UpdateWithSideEffects */Block.__(2, [
                                /* record */[
                                  /* xIndex */state[/* xIndex */0],
                                  /* xDelta */state[/* xDelta */1],
                                  /* inputGain */state[/* inputGain */2],
                                  /* outputGain */state[/* outputGain */3],
                                  /* filterInput */action[0],
                                  /* visualInput */state[/* visualInput */5],
                                  /* channelToRead */state[/* channelToRead */6],
                                  /* allowedPitchClasses */state[/* allowedPitchClasses */7],
                                  /* filterBank */state[/* filterBank */8],
                                  /* canvasRef */state[/* canvasRef */9],
                                  /* timerId */state[/* timerId */10]
                                ],
                                (function (self) {
                                    var partial_arg = self[/* state */1][/* filterInput */4];
                                    return maybeMapFilterBank((function (param) {
                                                  return Audio$Gayer.connectFilterBank(partial_arg, param);
                                                }), self[/* state */1][/* filterBank */8]);
                                  })
                              ]);
                  case 1 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* xIndex */state[/* xIndex */0],
                                  /* xDelta */state[/* xDelta */1],
                                  /* inputGain */state[/* inputGain */2],
                                  /* outputGain */state[/* outputGain */3],
                                  /* filterInput */state[/* filterInput */4],
                                  /* visualInput */action[0],
                                  /* channelToRead */state[/* channelToRead */6],
                                  /* allowedPitchClasses */state[/* allowedPitchClasses */7],
                                  /* filterBank */state[/* filterBank */8],
                                  /* canvasRef */state[/* canvasRef */9],
                                  /* timerId */state[/* timerId */10]
                                ]]);
                  case 2 : 
                      return /* UpdateWithSideEffects */Block.__(2, [
                                /* record */[
                                  /* xIndex */state[/* xIndex */0],
                                  /* xDelta */state[/* xDelta */1],
                                  /* inputGain */state[/* inputGain */2],
                                  /* outputGain */state[/* outputGain */3],
                                  /* filterInput */state[/* filterInput */4],
                                  /* visualInput */state[/* visualInput */5],
                                  /* channelToRead */state[/* channelToRead */6],
                                  /* allowedPitchClasses */state[/* allowedPitchClasses */7],
                                  /* filterBank : Some */[action[0]],
                                  /* canvasRef */state[/* canvasRef */9],
                                  /* timerId */state[/* timerId */10]
                                ],
                                (function (self) {
                                    var partial_arg = self[/* state */1][/* filterInput */4];
                                    return maybeMapFilterBank((function (param) {
                                                  return Audio$Gayer.connectFilterBank(partial_arg, param);
                                                }), self[/* state */1][/* filterBank */8]);
                                  })
                              ]);
                  case 3 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* xIndex */Caml_int32.mod_(action[0], width),
                                  /* xDelta */state[/* xDelta */1],
                                  /* inputGain */state[/* inputGain */2],
                                  /* outputGain */state[/* outputGain */3],
                                  /* filterInput */state[/* filterInput */4],
                                  /* visualInput */state[/* visualInput */5],
                                  /* channelToRead */state[/* channelToRead */6],
                                  /* allowedPitchClasses */state[/* allowedPitchClasses */7],
                                  /* filterBank */state[/* filterBank */8],
                                  /* canvasRef */state[/* canvasRef */9],
                                  /* timerId */state[/* timerId */10]
                                ]]);
                  case 4 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* xIndex */state[/* xIndex */0],
                                  /* xDelta */action[0],
                                  /* inputGain */state[/* inputGain */2],
                                  /* outputGain */state[/* outputGain */3],
                                  /* filterInput */state[/* filterInput */4],
                                  /* visualInput */state[/* visualInput */5],
                                  /* channelToRead */state[/* channelToRead */6],
                                  /* allowedPitchClasses */state[/* allowedPitchClasses */7],
                                  /* filterBank */state[/* filterBank */8],
                                  /* canvasRef */state[/* canvasRef */9],
                                  /* timerId */state[/* timerId */10]
                                ]]);
                  
                }
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  setCanvasRef ,
  component ,
  maybeUpdateCanvas ,
  maybeMapFilterBank ,
  clearCanvas ,
  drawCanvas ,
  make ,
  
}
/* component Not a pure module */
