// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

function readAllBitsOfInt($staropt$star, input) {
  var outLength = $staropt$star !== undefined ? $staropt$star : 12;
  if (input <= 0) {
    return Caml_array.caml_make_vect(outLength, false);
  } else {
    var x = input;
    var i = 0;
    var bits = Caml_array.caml_make_vect(outLength, false);
    while(x > 0) {
      Caml_array.caml_array_set(bits, i, (x & 1) === 1);
      x = (x >>> 1);
      i = i + 1 | 0;
    };
    return bits;
  }
}

function binaryToGray(i) {
  return i ^ (i >>> 1);
}

function grayToBinary(i) {
  var num = i;
  var mask = (i >>> 1);
  while(mask !== 0) {
    num = num ^ mask;
    mask = (mask >>> 1);
  };
  return num;
}

export {
  readAllBitsOfInt ,
  binaryToGray ,
  grayToBinary ,
  
}
/* No side effect */
