// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as Json_encode from "@glennsl/bs-json/src/Json_encode.bs.js";
import * as DrawCommand$Gayer from "./DrawCommand.bs.js";

function cameraOptions(json) {
  var partial_arg = DrawCommand$Gayer.DecodeDrawCommand[/* rect */2];
  return /* record */[
          /* sourceLayerKey */Json_decode.field("source", Json_decode.string, json),
          /* sourceRect */Json_decode.field("sourceRect", DrawCommand$Gayer.DecodeDrawCommand[/* rect */2], json),
          /* destRect */Json_decode.optional((function (param) {
                  return Json_decode.field("destRect", partial_arg, param);
                }), json),
          /* sourceXDelta */Json_decode.field("sourceXDelta", DrawCommand$Gayer.DecodeDrawCommand[/* length */1], json),
          /* sourceYDelta */Json_decode.field("sourceYDelta", DrawCommand$Gayer.DecodeDrawCommand[/* length */1], json),
          /* destXDelta */Json_decode.field("destXDelta", DrawCommand$Gayer.DecodeDrawCommand[/* length */1], json),
          /* destYDelta */Json_decode.field("destYDelta", DrawCommand$Gayer.DecodeDrawCommand[/* length */1], json)
        ];
}

var DecodeCameraOptions = /* module */[/* cameraOptions */cameraOptions];

function cameraOptions$1(r) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "source",
                r[/* sourceLayerKey */0]
              ],
              /* :: */[
                /* tuple */[
                  "sourceRect",
                  DrawCommand$Gayer.EncodeDrawCommand[/* rect */2](r[/* sourceRect */1])
                ],
                /* :: */[
                  /* tuple */[
                    "destRect",
                    Json_encode.nullable(DrawCommand$Gayer.EncodeDrawCommand[/* rect */2], r[/* destRect */2])
                  ],
                  /* :: */[
                    /* tuple */[
                      "sourceXDelta",
                      DrawCommand$Gayer.EncodeDrawCommand[/* length */1](r[/* sourceXDelta */3])
                    ],
                    /* :: */[
                      /* tuple */[
                        "sourceYDelta",
                        DrawCommand$Gayer.EncodeDrawCommand[/* length */1](r[/* sourceYDelta */4])
                      ],
                      /* :: */[
                        /* tuple */[
                          "destXDelta",
                          DrawCommand$Gayer.EncodeDrawCommand[/* length */1](r[/* destXDelta */5])
                        ],
                        /* :: */[
                          /* tuple */[
                            "destYDelta",
                            DrawCommand$Gayer.EncodeDrawCommand[/* length */1](r[/* destYDelta */6])
                          ],
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var EncodeCameraOptions = /* module */[/* cameraOptions */cameraOptions$1];

var slitscanDefaults = /* record */[
  /* sourceLayerKey */"webcam",
  /* sourceRect : record */[
    /* x : Divide */Block.__(6, [
        /* Width */0,
        /* Constant */Block.__(0, [2])
      ]),
    /* y : Pixels */Block.__(2, [0]),
    /* w : Pixels */Block.__(2, [1]),
    /* h : Height */1
  ],
  /* destRect *//* record */[
    /* x : Pixels */Block.__(2, [0]),
    /* y : Pixels */Block.__(2, [0]),
    /* w : Pixels */Block.__(2, [1]),
    /* h : Height */1
  ],
  /* sourceXDelta : Pixels */Block.__(2, [0]),
  /* sourceYDelta : Pixels */Block.__(2, [0]),
  /* destXDelta : Pixels */Block.__(2, [1]),
  /* destYDelta : Pixels */Block.__(2, [0])
];

export {
  slitscanDefaults ,
  DecodeCameraOptions ,
  EncodeCameraOptions ,
  
}
/* Json_encode Not a pure module */
