// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as MIDICanvas$Gayer from "./MIDICanvas.bs.js";
import * as AnalysisCanvas$Gayer from "./AnalysisCanvas.bs.js";

var component = ReasonReact.statelessComponent("LayerContent");

function make(layerKey, audioCtx, audioGraph, setRef, _, millisPerTick, _$1, height, layerContent, _$2) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var tmp;
              if (typeof layerContent === "number") {
                tmp = ReasonReact.element(undefined, undefined, MIDICanvas$Gayer.make(setRef, /* array */[]));
              } else {
                switch (layerContent.tag | 0) {
                  case 2 : 
                      tmp = React.createElement("video", {
                            ref: setRef,
                            autoPlay: true,
                            height: "120",
                            muted: true,
                            width: "120"
                          });
                      break;
                  case 3 : 
                      tmp = React.createElement("img", {
                            ref: setRef,
                            height: "120",
                            src: layerContent[0],
                            width: "120"
                          });
                      break;
                  case 4 : 
                      tmp = React.createElement("video", {
                            ref: setRef,
                            autoPlay: true,
                            height: "120",
                            loop: true,
                            muted: true,
                            src: layerContent[0],
                            width: "120"
                          });
                      break;
                  case 5 : 
                      tmp = ReasonReact.element(undefined, undefined, AnalysisCanvas$Gayer.make(height, layerKey, audioCtx, audioGraph, layerContent[0], millisPerTick, setRef, /* array */[]));
                      break;
                  default:
                    tmp = null;
                }
              }
              return React.createElement("div", {
                          key: layerKey
                        }, tmp);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
