// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";
import * as MaterialUIIcons from "bs-material-ui-icons/src/MaterialUIIcons.js";
import * as MaterialUi_Button from "@jsiebern/bs-material-ui/src/MaterialUi_Button.bs.js";
import * as NewLayerMenu$Gayer from "./NewLayerMenu.bs.js";

function setRef(theRef, param) {
  if (theRef == null) {
    return /* () */0;
  } else {
    return Curry._1(param[/* send */3], /* SetAnchorEl */[theRef]);
  }
}

function sendOpen(_, param) {
  return Curry._1(param[/* send */3], /* Open */0);
}

var component = ReasonReact.reducerComponent("NewLayerButton-Gayer");

function make(onAdd, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, ReasonReact.element(undefined, Curry._1(self[/* handle */0], setRef), MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* Fab */3502759, undefined, undefined, undefined, undefined, undefined, undefined, Curry._1(self[/* handle */0], sendOpen), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUIIcons.Add[/* make */0](/* array */[]))])), ReasonReact.element(undefined, undefined, NewLayerMenu$Gayer.make((function (layer) {
                                    Curry._1(onAdd, layer);
                                    return Curry._1(self[/* send */3], /* Close */1);
                                  }), self[/* state */1][/* open_ */1], self[/* state */1][/* anchorEl */0], /* array */[])));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* anchorEl : record */[/* contents */undefined],
                      /* open_ */false
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* record */[
                              /* anchorEl */state[/* anchorEl */0],
                              /* open_ */false
                            ]]);
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* anchorEl */state[/* anchorEl */0],
                              /* open_ */true
                            ]]);
                }
              } else {
                var el = action[0];
                return /* SideEffects */Block.__(1, [(function (self) {
                              self[/* state */1][/* anchorEl */0][0] = Js_primitive.some(el);
                              return /* () */0;
                            })]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  setRef ,
  sendOpen ,
  component ,
  make ,
  
}
/* component Not a pure module */
