// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Hashtbl from "bs-platform/lib/es6/hashtbl.js";
import * as Audio$Gayer from "./Audio.bs.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as Json_encode from "@glennsl/bs-json/src/Json_encode.bs.js";
import * as Layer$Gayer from "./Layer.bs.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Canvas$Gayer from "./Canvas.bs.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";
import * as Container$Gayer from "./DnD/Container.bs.js";
import * as IntSlider$Gayer from "./IntSlider.bs.js";
import * as MaterialUIIcons from "bs-material-ui-icons/src/MaterialUIIcons.js";
import * as FloatSlider$Gayer from "./FloatSlider.bs.js";
import * as MaterialUi_Switch from "@jsiebern/bs-material-ui/src/MaterialUi_Switch.bs.js";
import * as MaterialUi_FormGroup from "@jsiebern/bs-material-ui/src/MaterialUi_FormGroup.bs.js";
import * as MaterialUi_FormLabel from "@jsiebern/bs-material-ui/src/MaterialUi_FormLabel.bs.js";
import * as MaterialUi_Typography from "@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js";
import * as AudioInputSelect$Gayer from "./AudioInputSelect.bs.js";
import * as MaterialUi_FormControl from "@jsiebern/bs-material-ui/src/MaterialUi_FormControl.bs.js";
import * as MaterialUi_ExpansionPanel from "@jsiebern/bs-material-ui/src/MaterialUi_ExpansionPanel.bs.js";
import * as MaterialUi_FormControlLabel from "@jsiebern/bs-material-ui/src/MaterialUi_FormControlLabel.bs.js";
import * as MaterialUi_ExpansionPanelDetails from "@jsiebern/bs-material-ui/src/MaterialUi_ExpansionPanelDetails.bs.js";
import * as MaterialUi_ExpansionPanelSummary from "@jsiebern/bs-material-ui/src/MaterialUi_ExpansionPanelSummary.bs.js";

var match = Canvas$Gayer.defaultSize === 120;

var defaultParams_008 = /* q */Audio$Gayer.qForBinsPerOctave(match ? Canvas$Gayer.defaultSize / 5 | 0 : Canvas$Gayer.defaultSize / 10 | 0);

var defaultParams = /* record */[
  /* readPosDelta */1,
  /* writePosDelta */1,
  /* readPosOffset */0,
  /* writePosOffset */0,
  /* millisPerTick */33,
  /* audioInputSetting : PinkNoise */0,
  /* inputGain */1.0,
  /* outputGain */0.2,
  defaultParams_008,
  /* transpose */0,
  /* shouldClear */true,
  /* layers : [] */0
];

function params(json) {
  var partial_arg = Layer$Gayer.DecodeLayer[/* layer */4];
  return /* record */[
          /* readPosDelta */Json_decode.field("readPosDelta", Json_decode.$$int, json),
          /* writePosDelta */Json_decode.field("writePosDelta", Json_decode.$$int, json),
          /* readPosOffset */Json_decode.field("readPosOffset", Json_decode.$$int, json),
          /* writePosOffset */Json_decode.field("writePosOffset", Json_decode.$$int, json),
          /* millisPerTick */Json_decode.field("millisPerTick", Json_decode.$$int, json),
          /* audioInputSetting */Json_decode.field("audioInputSetting", Audio$Gayer.AudioInput[/* DecodeAudioInput */1][/* audioInputSetting */0], json),
          /* inputGain */Json_decode.field("inputGain", Json_decode.$$float, json),
          /* outputGain */Json_decode.field("outputGain", Json_decode.$$float, json),
          /* q */Json_decode.field("q", Json_decode.$$float, json),
          /* transpose */Json_decode.field("transpose", Json_decode.$$int, json),
          /* shouldClear */Json_decode.field("shouldClear", Json_decode.bool, json),
          /* layers */Json_decode.field("layers", (function (param) {
                  return Json_decode.list(partial_arg, param);
                }), json)
        ];
}

var DecodeParams = /* module */[/* params */params];

function params$1(r) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "readPosDelta",
                r[/* readPosDelta */0]
              ],
              /* :: */[
                /* tuple */[
                  "writePosDelta",
                  r[/* writePosDelta */1]
                ],
                /* :: */[
                  /* tuple */[
                    "readPosOffset",
                    r[/* readPosOffset */2]
                  ],
                  /* :: */[
                    /* tuple */[
                      "writePosOffset",
                      r[/* writePosOffset */3]
                    ],
                    /* :: */[
                      /* tuple */[
                        "millisPerTick",
                        r[/* millisPerTick */4]
                      ],
                      /* :: */[
                        /* tuple */[
                          "audioInputSetting",
                          Curry._1(Audio$Gayer.AudioInput[/* EncodeAudioInput */0][/* audioInputSetting */0], r[/* audioInputSetting */5])
                        ],
                        /* :: */[
                          /* tuple */[
                            "inputGain",
                            r[/* inputGain */6]
                          ],
                          /* :: */[
                            /* tuple */[
                              "outputGain",
                              r[/* outputGain */7]
                            ],
                            /* :: */[
                              /* tuple */[
                                "q",
                                r[/* q */8]
                              ],
                              /* :: */[
                                /* tuple */[
                                  "transpose",
                                  r[/* transpose */9]
                                ],
                                /* :: */[
                                  /* tuple */[
                                    "shouldClear",
                                    r[/* shouldClear */10]
                                  ],
                                  /* :: */[
                                    /* tuple */[
                                      "layers",
                                      Json_encode.list(Layer$Gayer.EncodeLayer[/* layer */3], r[/* layers */11])
                                    ],
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var EncodeParams = /* module */[/* params */params$1];

var component = ReasonReact.statelessComponent("Params");

function make(params, onMoveCard, onSetRef, onChangeLayer, onSetParams, getAudio, saveTick, rootWidth, rootHeight, millisPerAudioTick, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, MaterialUi_ExpansionPanel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, {
                                  marginBottom: "12px"
                                }, /* array */[
                                  ReasonReact.element(undefined, undefined, MaterialUi_ExpansionPanelSummary.make(undefined, undefined, undefined, Js_primitive.some(ReasonReact.element(undefined, undefined, MaterialUIIcons.ExpandMore[/* make */0](/* array */[]))), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, undefined, /* Inherit */-72987685, undefined, undefined, undefined, undefined, undefined, /* Subheading */148169314, undefined, undefined, /* array */["Global Settings"]))])),
                                  ReasonReact.element(undefined, undefined, MaterialUi_ExpansionPanelDetails.make(undefined, undefined, undefined, /* array */[
                                            ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, /* `String */[
                                                      -976970511,
                                                      "fieldset"
                                                    ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                                      ReasonReact.element(undefined, undefined, MaterialUi_FormLabel.make(undefined, /* `String */[
                                                                -976970511,
                                                                "legend"
                                                              ], undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Graphics"])),
                                                      ReasonReact.element(undefined, undefined, MaterialUi_FormGroup.make(undefined, true, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_FormControlLabel.make(undefined, undefined, Js_primitive.some(ReasonReact.element(undefined, undefined, MaterialUi_Switch.make(/* `Bool */[
                                                                                      737456202,
                                                                                      params[/* shouldClear */10]
                                                                                    ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_, value) {
                                                                                        return Curry._1(onSetParams, /* record */[
                                                                                                    /* readPosDelta */params[/* readPosDelta */0],
                                                                                                    /* writePosDelta */params[/* writePosDelta */1],
                                                                                                    /* readPosOffset */params[/* readPosOffset */2],
                                                                                                    /* writePosOffset */params[/* writePosOffset */3],
                                                                                                    /* millisPerTick */params[/* millisPerTick */4],
                                                                                                    /* audioInputSetting */params[/* audioInputSetting */5],
                                                                                                    /* inputGain */params[/* inputGain */6],
                                                                                                    /* outputGain */params[/* outputGain */7],
                                                                                                    /* q */params[/* q */8],
                                                                                                    /* transpose */params[/* transpose */9],
                                                                                                    /* shouldClear */value,
                                                                                                    /* layers */params[/* layers */11]
                                                                                                  ]);
                                                                                      }), undefined, "shouldClear", undefined, undefined, /* array */[]))), undefined, undefined, "Clear between frames", undefined, undefined, undefined, undefined, undefined, /* array */[]))])),
                                                      ReasonReact.element(undefined, undefined, IntSlider$Gayer.make(0, rootWidth - 1 | 0, undefined, "Read position offset", params[/* readPosOffset */2], 1, (function (readPosOffset) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */readPosOffset,
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[])),
                                                      ReasonReact.element(undefined, undefined, IntSlider$Gayer.make(0, rootWidth - 1 | 0, undefined, "Write position offset", params[/* writePosOffset */3], undefined, (function (writePosOffset) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */writePosOffset,
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[])),
                                                      ReasonReact.element(undefined, undefined, IntSlider$Gayer.make((-rootWidth | 0) + 1 | 0, rootWidth - 1 | 0, undefined, "Read position delta", params[/* readPosDelta */0], undefined, (function (readPosDelta) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */readPosDelta,
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[])),
                                                      ReasonReact.element(undefined, undefined, IntSlider$Gayer.make((-rootWidth | 0) + 1 | 0, rootWidth - 1 | 0, undefined, "Write position delta", params[/* writePosDelta */1], undefined, (function (writePosDelta) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */writePosDelta,
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[]))
                                                    ])),
                                            ReasonReact.element(undefined, undefined, MaterialUi_FormControl.make(undefined, /* `String */[
                                                      -976970511,
                                                      "fieldset"
                                                    ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                                      ReasonReact.element(undefined, undefined, MaterialUi_FormLabel.make(undefined, /* `String */[
                                                                -976970511,
                                                                "legend"
                                                              ], undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Audio"])),
                                                      ReasonReact.element(undefined, undefined, AudioInputSelect$Gayer.make(params[/* audioInputSetting */5], (function (audioInputSetting) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */audioInputSetting,
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[])),
                                                      ReasonReact.element(undefined, undefined, FloatSlider$Gayer.make(undefined, undefined, "Input gain", params[/* inputGain */6], undefined, (function (inputGain) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */inputGain,
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[])),
                                                      ReasonReact.element(undefined, undefined, FloatSlider$Gayer.make(undefined, undefined, "Output gain", params[/* outputGain */7], undefined, (function (outputGain) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */outputGain,
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[])),
                                                      ReasonReact.element(undefined, undefined, FloatSlider$Gayer.make(1.0, 200.0, "Q", params[/* q */8], undefined, (function (q) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */q,
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[])),
                                                      ReasonReact.element(undefined, undefined, IntSlider$Gayer.make(-119, 119, undefined, "Transpose", params[/* transpose */9], undefined, (function (transpose) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */params[/* millisPerTick */4],
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */transpose,
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[])),
                                                      ReasonReact.element(undefined, undefined, IntSlider$Gayer.make(10, 100, undefined, "Milliseconds per tick", params[/* millisPerTick */4], undefined, (function (millisPerTick) {
                                                                  return Curry._1(onSetParams, /* record */[
                                                                              /* readPosDelta */params[/* readPosDelta */0],
                                                                              /* writePosDelta */params[/* writePosDelta */1],
                                                                              /* readPosOffset */params[/* readPosOffset */2],
                                                                              /* writePosOffset */params[/* writePosOffset */3],
                                                                              /* millisPerTick */millisPerTick,
                                                                              /* audioInputSetting */params[/* audioInputSetting */5],
                                                                              /* inputGain */params[/* inputGain */6],
                                                                              /* outputGain */params[/* outputGain */7],
                                                                              /* q */params[/* q */8],
                                                                              /* transpose */params[/* transpose */9],
                                                                              /* shouldClear */params[/* shouldClear */10],
                                                                              /* layers */params[/* layers */11]
                                                                            ]);
                                                                }), /* array */[]))
                                                    ]))
                                          ]))
                                ])), ReasonReact.element(undefined, undefined, Container$Gayer.make(List.map((function (layer) {
                                        var id = "card" + String(Hashtbl.hash(layer));
                                        return /* record */[
                                                /* id */id,
                                                /* layer */layer
                                              ];
                                      }), params[/* layers */11]), onMoveCard, onChangeLayer, onSetRef, getAudio, rootWidth, rootHeight, millisPerAudioTick, saveTick, /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  defaultParams ,
  DecodeParams ,
  EncodeParams ,
  component ,
  make ,
  
}
/* defaultParams Not a pure module */
