// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Layer$Gayer from "./Layer.bs.js";
import * as Music$Gayer from "./Music.bs.js";
import * as Canvas$Gayer from "./Canvas.bs.js";
import * as Params$Gayer from "./Params.bs.js";
import * as MIDICanvas$Gayer from "./MIDICanvas.bs.js";

function img(url) {
  return /* record */[
          /* content : Image */Block.__(3, [url]),
          /* alpha */Layer$Gayer.defaultLayer[/* alpha */1],
          /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2],
          /* rotation */Layer$Gayer.defaultLayer[/* rotation */3],
          /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4],
          /* filters */Layer$Gayer.defaultLayer[/* filters */5]
        ];
}

function video(url) {
  return /* record */[
          /* content : Video */Block.__(4, [url]),
          /* alpha */Layer$Gayer.defaultLayer[/* alpha */1],
          /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2],
          /* rotation */Layer$Gayer.defaultLayer[/* rotation */3],
          /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4],
          /* filters */Layer$Gayer.defaultLayer[/* filters */5]
        ];
}

var reader_000 = /* content : Reader */Block.__(7, [/* R */0]);

var reader_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var reader_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var reader_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var reader = /* record */[
  reader_000,
  /* alpha */1.0,
  /* compositeOperation : Multiply */11,
  reader_003,
  reader_004,
  reader_005
];

function pitchFilter(pc) {
  return /* record */[
          /* content : PitchClasses */Block.__(6, [pc]),
          /* alpha */Layer$Gayer.defaultLayer[/* alpha */1],
          /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2],
          /* rotation */Layer$Gayer.defaultLayer[/* rotation */3],
          /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4],
          /* filters */Layer$Gayer.defaultLayer[/* filters */5]
        ];
}

function fill($staropt$star, fillStyle) {
  var alpha = $staropt$star !== undefined ? $staropt$star : 1.0;
  return /* record */[
          /* content : Fill */Block.__(0, [fillStyle]),
          /* alpha */alpha,
          /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2],
          /* rotation */Layer$Gayer.defaultLayer[/* rotation */3],
          /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4],
          /* filters */Layer$Gayer.defaultLayer[/* filters */5]
        ];
}

function draw($staropt$star, cmds) {
  var alpha = $staropt$star !== undefined ? $staropt$star : 1.0;
  return /* record */[
          /* content : Draw */Block.__(1, [cmds]),
          /* alpha */alpha,
          /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2],
          /* rotation */Layer$Gayer.defaultLayer[/* rotation */3],
          /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4],
          /* filters */Layer$Gayer.defaultLayer[/* filters */5]
        ];
}

var analyzer_000 = /* content : Analysis */Block.__(5, [/* Mic */2]);

var analyzer_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var analyzer_002 = /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2];

var analyzer_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var analyzer_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var analyzer_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var analyzer = /* record */[
  analyzer_000,
  analyzer_001,
  analyzer_002,
  analyzer_003,
  analyzer_004,
  analyzer_005
];

var webcam_000 = /* content : Webcam */Block.__(2, [/* record */[/* slitscan */undefined]]);

var webcam_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var webcam_002 = /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2];

var webcam_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var webcam_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var webcam_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var webcam = /* record */[
  webcam_000,
  webcam_001,
  webcam_002,
  webcam_003,
  webcam_004,
  webcam_005
];

var slitscan_000 = /* content : Webcam */Block.__(2, [/* record */[/* slitscan *//* record */[/* x */320]]]);

var slitscan_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var slitscan_002 = /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2];

var slitscan_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var slitscan_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var slitscan_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var slitscan = /* record */[
  slitscan_000,
  slitscan_001,
  slitscan_002,
  slitscan_003,
  slitscan_004,
  slitscan_005
];

var hubble = img("media/hubble_ultra_deep_field.jpg");

var spacy_001 = /* :: */[
  pitchFilter(Music$Gayer.cMajor),
  /* :: */[
    reader,
    /* [] */0
  ]
];

var spacy = /* :: */[
  hubble,
  spacy_001
];

var drawSelfFullScreen = /* DrawImage */Block.__(4, [
    /* Self */0,
    /* record */[
      /* x : Pixels */Block.__(1, [0]),
      /* y : Pixels */Block.__(1, [0]),
      /* w : Width */0,
      /* h : Height */1
    ]
  ]);

var init = img("media/harmony.png");

var init$1 = draw(undefined, /* :: */[
      /* DrawImage */Block.__(4, [
          /* Self */0,
          /* record */[
            /* x : Pixels */Block.__(1, [0]),
            /* y : Pixels */Block.__(1, [-24]),
            /* w : Width */0,
            /* h : Height */1
          ]
        ]),
      /* :: */[
        /* DrawImage */Block.__(4, [
            /* Self */0,
            /* record */[
              /* x : Pixels */Block.__(1, [0]),
              /* y : Pixels */Block.__(1, [-48]),
              /* w : Width */0,
              /* h : Height */1
            ]
          ]),
        /* [] */0
      ]
    ]);

var harmony_000 = /* record */[
  /* content */init[/* content */0],
  /* alpha */1.0,
  /* compositeOperation : SourceOver */0,
  /* rotation */init[/* rotation */3],
  /* transformMatrix : record */[
    /* horizontalScaling */Canvas$Gayer.defaultTransform[/* horizontalScaling */0],
    /* horizontalSkewing */Canvas$Gayer.defaultTransform[/* horizontalSkewing */1],
    /* verticalSkewing */Canvas$Gayer.defaultTransform[/* verticalSkewing */2],
    /* verticalScaling */Canvas$Gayer.defaultTransform[/* verticalScaling */3],
    /* horizontalMoving */Canvas$Gayer.defaultTransform[/* horizontalMoving */4],
    /* verticalMoving */48.0
  ],
  /* filters */"blur(2px)"
];

var harmony_001 = /* :: */[
  /* record */[
    /* content */init$1[/* content */0],
    /* alpha */0.5,
    /* compositeOperation : Difference */20,
    /* rotation */init$1[/* rotation */3],
    /* transformMatrix */init$1[/* transformMatrix */4],
    /* filters */init$1[/* filters */5]
  ],
  /* :: */[
    pitchFilter(Music$Gayer.cMajor),
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var harmony = /* :: */[
  harmony_000,
  harmony_001
];

var rotateLayer = draw(undefined, /* :: */[
      /* Translate */Block.__(3, [
          /* Pixels */Block.__(1, [Canvas$Gayer.defaultSize / 2 | 0]),
          /* Pixels */Block.__(1, [Canvas$Gayer.defaultSize / 2 | 0])
        ]),
      /* :: */[
        /* Rotate */Block.__(2, [Layer$Gayer.oneCompleteTurnAfterNTicks(Canvas$Gayer.defaultSize / 2 | 0)]),
        /* :: */[
          /* Translate */Block.__(3, [
              /* Negate */Block.__(3, [/* Pixels */Block.__(1, [Canvas$Gayer.defaultSize / 2 | 0])]),
              /* Negate */Block.__(3, [/* Pixels */Block.__(1, [Canvas$Gayer.defaultSize / 2 | 0])])
            ]),
          /* :: */[
            drawSelfFullScreen,
            /* [] */0
          ]
        ]
      ]
    ]);

var init$2 = draw(undefined, /* :: */[
      drawSelfFullScreen,
      /* [] */0
    ]);

var blurLayer_000 = /* content */init$2[/* content */0];

var blurLayer_001 = /* alpha */init$2[/* alpha */1];

var blurLayer_002 = /* compositeOperation */init$2[/* compositeOperation */2];

var blurLayer_003 = /* rotation */init$2[/* rotation */3];

var blurLayer_004 = /* transformMatrix */init$2[/* transformMatrix */4];

var blurLayer = /* record */[
  blurLayer_000,
  blurLayer_001,
  blurLayer_002,
  blurLayer_003,
  blurLayer_004,
  /* filters */"blur(2px)"
];

var init$3 = draw(undefined, /* :: */[
      /* DrawImageSourceDest */Block.__(5, [
          /* Self */0,
          /* record */[
            /* x : Add */Block.__(4, [
                /* Width */0,
                /* Pixels */Block.__(1, [-1])
              ]),
            /* y : Pixels */Block.__(1, [0]),
            /* w : Pixels */Block.__(1, [1]),
            /* h : Height */1
          ],
          /* record */[
            /* x : Add */Block.__(4, [
                /* Width */0,
                /* Pixels */Block.__(1, [-1])
              ]),
            /* y : Pixels */Block.__(1, [0]),
            /* w : Pixels */Block.__(1, [1]),
            /* h : Height */1
          ]
        ]),
      /* [] */0
    ]);

var squareColumnLayer_000 = /* content */init$3[/* content */0];

var squareColumnLayer_003 = /* rotation */init$3[/* rotation */3];

var squareColumnLayer_004 = /* transformMatrix */init$3[/* transformMatrix */4];

var squareColumnLayer_005 = /* filters */init$3[/* filters */5];

var squareColumnLayer = /* record */[
  squareColumnLayer_000,
  /* alpha */0.75,
  /* compositeOperation : Multiply */11,
  squareColumnLayer_003,
  squareColumnLayer_004,
  squareColumnLayer_005
];

var squareLayer_000 = /* content : Draw */Block.__(1, [/* :: */[
      /* DrawImage */Block.__(4, [
          /* Self */0,
          /* record */[
            /* x : Pixels */Block.__(1, [0]),
            /* y : Pixels */Block.__(1, [0]),
            /* w : Width */0,
            /* h : Height */1
          ]
        ]),
      /* [] */0
    ]]);

var squareLayer_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var squareLayer_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var squareLayer_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var squareLayer_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var squareLayer = /* record */[
  squareLayer_000,
  squareLayer_001,
  /* compositeOperation : Multiply */11,
  squareLayer_003,
  squareLayer_004,
  squareLayer_005
];

function singleNoteDrawCommands() {
  return /* :: */[
          /* SetFillStyle */Block.__(0, ["red"]),
          /* :: */[
            /* FillRect */Block.__(1, [/* record */[
                  /* x : Pixels */Block.__(1, [0]),
                  /* y : Note */Block.__(2, [60]),
                  /* w : Width */0,
                  /* h : Pixels */Block.__(1, [1])
                ]]),
            /* [] */0
          ]
        ];
}

function singleNoteLayer(note) {
  return /* record */[
          /* content : Draw */Block.__(1, [singleNoteDrawCommands(note)]),
          /* alpha */Layer$Gayer.defaultLayer[/* alpha */1],
          /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2],
          /* rotation */Layer$Gayer.defaultLayer[/* rotation */3],
          /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4],
          /* filters */Layer$Gayer.defaultLayer[/* filters */5]
        ];
}

var singleNote_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var singleNote_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var singleNote_002 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2];

var singleNote_003 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3];

var singleNote_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var singleNote_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var singleNote_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var singleNote_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var singleNote_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var singleNote_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var singleNote_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var singleNote_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var singleNote_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var singleNote_013 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13];

var singleNote_014 = /* layers : :: */[
  singleNoteLayer(60),
  /* :: */[
    reader,
    /* [] */0
  ]
];

var singleNote = /* record */[
  singleNote_000,
  singleNote_001,
  singleNote_002,
  singleNote_003,
  singleNote_004,
  singleNote_005,
  singleNote_006,
  singleNote_007,
  singleNote_008,
  singleNote_009,
  singleNote_010,
  singleNote_011,
  singleNote_012,
  singleNote_013,
  singleNote_014
];

var historyLayer_000 = /* content : Draw */Block.__(1, [/* :: */[
      /* DrawImage */Block.__(4, [
          /* Self */0,
          /* record */[
            /* x : Pixels */Block.__(1, [-1]),
            /* y : Pixels */Block.__(1, [0]),
            /* w : Width */0,
            /* h : Height */1
          ]
        ]),
      /* [] */0
    ]]);

var historyLayer_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var historyLayer_002 = /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2];

var historyLayer_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var historyLayer_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var historyLayer_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var historyLayer = /* record */[
  historyLayer_000,
  historyLayer_001,
  historyLayer_002,
  historyLayer_003,
  historyLayer_004,
  historyLayer_005
];

var historyBackAndForthLayer_000 = /* content : Draw */Block.__(1, [/* :: */[
      /* DrawImageSourceDest */Block.__(5, [
          /* Self */0,
          /* record */[
            /* x : Divide */Block.__(5, [
                /* Width */0,
                /* Constant */Block.__(0, [2])
              ]),
            /* y : Pixels */Block.__(1, [0]),
            /* w : Divide */Block.__(5, [
                /* Width */0,
                /* Constant */Block.__(0, [2])
              ]),
            /* h : Height */1
          ],
          /* record */[
            /* x : Add */Block.__(4, [
                /* Divide */Block.__(5, [
                    /* Width */0,
                    /* Constant */Block.__(0, [2])
                  ]),
                /* Pixels */Block.__(1, [1])
              ]),
            /* y : Pixels */Block.__(1, [0]),
            /* w : Divide */Block.__(5, [
                /* Width */0,
                /* Constant */Block.__(0, [2])
              ]),
            /* h : Height */1
          ]
        ]),
      /* :: */[
        /* DrawImageSourceDest */Block.__(5, [
            /* Self */0,
            /* record */[
              /* x : Pixels */Block.__(1, [1]),
              /* y : Pixels */Block.__(1, [0]),
              /* w : Divide */Block.__(5, [
                  /* Width */0,
                  /* Constant */Block.__(0, [2])
                ]),
              /* h : Height */1
            ],
            /* record */[
              /* x : Pixels */Block.__(1, [0]),
              /* y : Pixels */Block.__(1, [0]),
              /* w : Divide */Block.__(5, [
                  /* Width */0,
                  /* Constant */Block.__(0, [2])
                ]),
              /* h : Height */1
            ]
          ]),
        /* [] */0
      ]
    ]]);

var historyBackAndForthLayer_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var historyBackAndForthLayer_002 = /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2];

var historyBackAndForthLayer_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var historyBackAndForthLayer_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var historyBackAndForthLayer_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var historyBackAndForthLayer = /* record */[
  historyBackAndForthLayer_000,
  historyBackAndForthLayer_001,
  historyBackAndForthLayer_002,
  historyBackAndForthLayer_003,
  historyBackAndForthLayer_004,
  historyBackAndForthLayer_005
];

var drosteLayer_000 = /* content : Draw */Block.__(1, [/* :: */[
      /* DrawImage */Block.__(4, [
          /* Self */0,
          /* record */[
            /* x : Pixels */Block.__(1, [1]),
            /* y : Pixels */Block.__(1, [1]),
            /* w : Add */Block.__(4, [
                /* Width */0,
                /* Pixels */Block.__(1, [-1])
              ]),
            /* h : Add */Block.__(4, [
                /* Height */1,
                /* Pixels */Block.__(1, [-1])
              ])
          ]
        ]),
      /* [] */0
    ]]);

var drosteLayer_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var drosteLayer_002 = /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2];

var drosteLayer_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var drosteLayer_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var drosteLayer_005 = /* filters */"hue-rotate(" + ((1.0 / 30.0 * (5.0 / 6.0)).toString() + "turn)");

var drosteLayer = /* record */[
  drosteLayer_000,
  drosteLayer_001,
  drosteLayer_002,
  drosteLayer_003,
  drosteLayer_004,
  drosteLayer_005
];

var allLayerTypes_001 = /* :: */[
  analyzer,
  /* :: */[
    webcam,
    /* :: */[
      slitscan,
      /* :: */[
        fill(0.0125, "white"),
        /* :: */[
          pitchFilter(Music$Gayer.cMajor),
          /* :: */[
            blurLayer,
            /* :: */[
              rotateLayer,
              /* :: */[
                squareColumnLayer,
                /* :: */[
                  squareLayer,
                  /* :: */[
                    reader,
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var allLayerTypes = /* :: */[
  hubble,
  allLayerTypes_001
];

var harmonyParams_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var harmonyParams_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var harmonyParams_002 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2];

var harmonyParams_003 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3];

var harmonyParams_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var harmonyParams_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var harmonyParams_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var harmonyParams_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var harmonyParams_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var harmonyParams_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var harmonyParams_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var harmonyParams_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var harmonyParams_013 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13];

var harmonyParams = /* record */[
  harmonyParams_000,
  harmonyParams_001,
  harmonyParams_002,
  harmonyParams_003,
  harmonyParams_004,
  harmonyParams_005,
  /* millisPerTick */25,
  harmonyParams_007,
  harmonyParams_008,
  harmonyParams_009,
  harmonyParams_010,
  harmonyParams_011,
  harmonyParams_012,
  harmonyParams_013,
  /* layers */harmony
];

var harmonyIntensified_000 = harmonyParams_000;

var harmonyIntensified_001 = harmonyParams_001;

var harmonyIntensified_002 = harmonyParams_002;

var harmonyIntensified_003 = harmonyParams_003;

var harmonyIntensified_004 = harmonyParams_004;

var harmonyIntensified_005 = harmonyParams_005;

var harmonyIntensified_007 = harmonyParams_007;

var harmonyIntensified_008 = harmonyParams_008;

var harmonyIntensified_009 = harmonyParams_009;

var harmonyIntensified_010 = harmonyParams_010;

var harmonyIntensified_011 = harmonyParams_011;

var harmonyIntensified_012 = harmonyParams_012;

var harmonyIntensified_013 = harmonyParams_013;

var harmonyIntensified_014 = /* layers : :: */[
  img("media/harmony_intensified.png"),
  /* :: */[
    reader,
    /* [] */0
  ]
];

var harmonyIntensified = /* record */[
  harmonyIntensified_000,
  harmonyIntensified_001,
  harmonyIntensified_002,
  harmonyIntensified_003,
  harmonyIntensified_004,
  harmonyIntensified_005,
  /* millisPerTick */25,
  harmonyIntensified_007,
  harmonyIntensified_008,
  harmonyIntensified_009,
  harmonyIntensified_010,
  harmonyIntensified_011,
  harmonyIntensified_012,
  harmonyIntensified_013,
  harmonyIntensified_014
];

var feedback_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var feedback_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var feedback_002 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2];

var feedback_003 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3];

var feedback_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var feedback_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var feedback_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var feedback_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var feedback_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var feedback_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var feedback_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var feedback_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var feedback_013 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13];

var feedback_014 = /* layers : :: */[
  webcam,
  /* :: */[
    /* record */[
      /* content : Analysis */Block.__(5, [/* Mic */2]),
      /* alpha */0.5,
      analyzer_002,
      analyzer_003,
      analyzer_004,
      analyzer_005
    ],
    /* :: */[
      pitchFilter(Music$Gayer.cMajor),
      /* :: */[
        reader,
        /* [] */0
      ]
    ]
  ]
];

var feedback = /* record */[
  feedback_000,
  feedback_001,
  feedback_002,
  feedback_003,
  feedback_004,
  feedback_005,
  feedback_006,
  /* audioInputSetting : Mic */2,
  feedback_008,
  feedback_009,
  feedback_010,
  feedback_011,
  feedback_012,
  feedback_013,
  feedback_014
];

var slitscanParams_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var slitscanParams_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var slitscanParams_004 = /* readPosOffset */Canvas$Gayer.defaultSize - 1 | 0;

var slitscanParams_005 = /* writePosOffset */Canvas$Gayer.defaultSize - 1 | 0;

var slitscanParams_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var slitscanParams_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var slitscanParams_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var slitscanParams_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var slitscanParams_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var slitscanParams_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var slitscanParams_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var slitscanParams_014 = /* layers : :: */[
  slitscan,
  /* :: */[
    /* record */[
      /* content : Analysis */Block.__(5, [/* Mic */2]),
      /* alpha */0.9,
      /* compositeOperation : Multiply */11,
      analyzer_003,
      analyzer_004,
      analyzer_005
    ],
    /* :: */[
      historyLayer,
      /* :: */[
        reader,
        /* [] */0
      ]
    ]
  ]
];

var slitscanParams = /* record */[
  slitscanParams_000,
  slitscanParams_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  slitscanParams_004,
  slitscanParams_005,
  slitscanParams_006,
  slitscanParams_007,
  slitscanParams_008,
  slitscanParams_009,
  slitscanParams_010,
  slitscanParams_011,
  slitscanParams_012,
  /* shouldClear */false,
  slitscanParams_014
];

var whiteboardParams_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var whiteboardParams_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var whiteboardParams_002 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2];

var whiteboardParams_003 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3];

var whiteboardParams_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var whiteboardParams_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var whiteboardParams_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var whiteboardParams_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var whiteboardParams_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var whiteboardParams_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var whiteboardParams_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var whiteboardParams_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var whiteboardParams_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var whiteboardParams_013 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13];

var whiteboardParams_014 = /* layers : :: */[
  /* record */[
    /* content : Webcam */Block.__(2, [/* record */[/* slitscan */undefined]]),
    webcam_001,
    webcam_002,
    webcam_003,
    webcam_004,
    /* filters */"contrast(300%) invert(100%)"
  ],
  /* :: */[
    pitchFilter(Music$Gayer.pentatonic),
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var whiteboardParams = /* record */[
  whiteboardParams_000,
  whiteboardParams_001,
  whiteboardParams_002,
  whiteboardParams_003,
  whiteboardParams_004,
  whiteboardParams_005,
  whiteboardParams_006,
  whiteboardParams_007,
  whiteboardParams_008,
  whiteboardParams_009,
  whiteboardParams_010,
  whiteboardParams_011,
  whiteboardParams_012,
  whiteboardParams_013,
  whiteboardParams_014
];

var isItACrime_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var isItACrime_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var isItACrime_002 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2];

var isItACrime_003 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3];

var isItACrime_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var isItACrime_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var isItACrime_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var isItACrime_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var isItACrime_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var isItACrime_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var isItACrime_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var isItACrime_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var isItACrime_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var isItACrime_013 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13];

var isItACrime_014 = /* layers : :: */[
  img("media/is_it_a_crime_large.png"),
  /* :: */[
    /* record */[
      /* content : Reader */Block.__(7, [/* A */3]),
      /* alpha */1.0,
      /* compositeOperation : Multiply */11,
      reader_003,
      reader_004,
      reader_005
    ],
    /* [] */0
  ]
];

var isItACrime = /* record */[
  isItACrime_000,
  isItACrime_001,
  isItACrime_002,
  isItACrime_003,
  isItACrime_004,
  isItACrime_005,
  isItACrime_006,
  isItACrime_007,
  isItACrime_008,
  isItACrime_009,
  isItACrime_010,
  isItACrime_011,
  isItACrime_012,
  isItACrime_013,
  isItACrime_014
];

var tughra_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var tughra_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var tughra_002 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2];

var tughra_003 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3];

var tughra_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var tughra_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var tughra_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var tughra_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var tughra_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var tughra_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var tughra_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var tughra_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var tughra_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var tughra_013 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13];

var tughra_014 = /* layers : :: */[
  img("media/suleiman.jpg"),
  /* :: */[
    reader,
    /* [] */0
  ]
];

var tughra = /* record */[
  tughra_000,
  tughra_001,
  tughra_002,
  tughra_003,
  tughra_004,
  tughra_005,
  tughra_006,
  tughra_007,
  tughra_008,
  tughra_009,
  tughra_010,
  tughra_011,
  tughra_012,
  tughra_013,
  tughra_014
];

var iChing_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var iChing_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var iChing_002 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2];

var iChing_003 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3];

var iChing_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var iChing_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var iChing_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var iChing_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var iChing_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var iChing_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var iChing_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var iChing_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var iChing_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var iChing_013 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13];

var iChing_014 = /* layers : :: */[
  img("media/king_wen.png"),
  /* :: */[
    pitchFilter(Music$Gayer.majorHexatonic),
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var iChing = /* record */[
  iChing_000,
  iChing_001,
  iChing_002,
  iChing_003,
  iChing_004,
  iChing_005,
  iChing_006,
  iChing_007,
  iChing_008,
  iChing_009,
  iChing_010,
  iChing_011,
  iChing_012,
  iChing_013,
  iChing_014
];

var history_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var history_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var history_004 = /* readPosOffset */Canvas$Gayer.defaultSize - 1 | 0;

var history_005 = /* writePosOffset */Canvas$Gayer.defaultSize - 1 | 0;

var history_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var history_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var history_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var history_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var history_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var history_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var history_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var history_014 = /* layers : :: */[
  analyzer,
  /* :: */[
    historyLayer,
    /* :: */[
      /* record */[
        /* content : Reader */Block.__(7, [/* R */0]),
        /* alpha */0.0,
        /* compositeOperation : Multiply */11,
        reader_003,
        reader_004,
        reader_005
      ],
      /* [] */0
    ]
  ]
];

var history = /* record */[
  history_000,
  history_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  history_004,
  history_005,
  history_006,
  history_007,
  history_008,
  history_009,
  history_010,
  history_011,
  history_012,
  /* shouldClear */false,
  history_014
];

var historyHalving_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var historyHalving_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var historyHalving_004 = /* readPosOffset */Canvas$Gayer.defaultSize - 1 | 0;

var historyHalving_005 = /* writePosOffset */Canvas$Gayer.defaultSize - 1 | 0;

var historyHalving_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var historyHalving_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var historyHalving_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var historyHalving_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var historyHalving_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var historyHalving_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var historyHalving_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var historyHalving_014 = /* layers : :: */[
  analyzer,
  /* :: */[
    squareColumnLayer,
    /* :: */[
      historyLayer,
      /* :: */[
        draw(undefined, /* :: */[
              /* DrawImage */Block.__(4, [
                  /* Self */0,
                  /* record */[
                    /* x : Pixels */Block.__(1, [0]),
                    /* y : Pixels */Block.__(1, [0]),
                    /* w : Divide */Block.__(5, [
                        /* Width */0,
                        /* Constant */Block.__(0, [2])
                      ]),
                    /* h : Height */1
                  ]
                ]),
              /* [] */0
            ]),
        /* :: */[
          /* record */[
            /* content : Reader */Block.__(7, [/* R */0]),
            /* alpha */0.0,
            /* compositeOperation : Multiply */11,
            reader_003,
            reader_004,
            reader_005
          ],
          /* [] */0
        ]
      ]
    ]
  ]
];

var historyHalving = /* record */[
  historyHalving_000,
  historyHalving_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  historyHalving_004,
  historyHalving_005,
  historyHalving_006,
  historyHalving_007,
  historyHalving_008,
  historyHalving_009,
  historyHalving_010,
  historyHalving_011,
  historyHalving_012,
  /* shouldClear */false,
  historyHalving_014
];

var debussyFile_000 = /* content : Analysis */Block.__(5, [/* AudioFile */Block.__(0, ["media/la_cathedrale_engloutie.m4a"])]);

var debussyFile_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var debussyFile_002 = /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2];

var debussyFile_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var debussyFile_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var debussyFile_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var debussyFile = /* record */[
  debussyFile_000,
  debussyFile_001,
  debussyFile_002,
  debussyFile_003,
  debussyFile_004,
  debussyFile_005
];

var debussy_000 = history_000;

var debussy_001 = history_001;

var debussy_004 = history_004;

var debussy_005 = history_005;

var debussy_006 = history_006;

var debussy_007 = history_007;

var debussy_008 = history_008;

var debussy_009 = history_009;

var debussy_010 = history_010;

var debussy_011 = history_011;

var debussy_012 = history_012;

var debussy_014 = /* layers : :: */[
  debussyFile,
  /* :: */[
    historyLayer,
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var debussy = /* record */[
  debussy_000,
  debussy_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  debussy_004,
  debussy_005,
  debussy_006,
  debussy_007,
  debussy_008,
  debussy_009,
  debussy_010,
  debussy_011,
  debussy_012,
  /* shouldClear */false,
  debussy_014
];

var droste_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var droste_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var droste_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var droste_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var droste_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var droste_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var droste_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var droste_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var droste_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var droste_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var droste_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var droste_014 = /* layers : :: */[
  analyzer,
  /* :: */[
    drosteLayer,
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var droste = /* record */[
  droste_000,
  droste_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  droste_004,
  droste_005,
  droste_006,
  droste_007,
  droste_008,
  droste_009,
  droste_010,
  droste_011,
  droste_012,
  /* shouldClear */false,
  droste_014
];

var midiKeyboard_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var midiKeyboard_002 = /* compositeOperation */Layer$Gayer.defaultLayer[/* compositeOperation */2];

var midiKeyboard_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var midiKeyboard_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var midiKeyboard_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var midiKeyboard = /* record */[
  /* content : MIDIKeyboard */0,
  midiKeyboard_001,
  midiKeyboard_002,
  midiKeyboard_003,
  midiKeyboard_004,
  midiKeyboard_005
];

var midiColors_000 = /* content : Draw */Block.__(1, [MIDICanvas$Gayer.makeNoteColors(MIDICanvas$Gayer.oneRainbow)]);

var midiColors_001 = /* alpha */Layer$Gayer.defaultLayer[/* alpha */1];

var midiColors_003 = /* rotation */Layer$Gayer.defaultLayer[/* rotation */3];

var midiColors_004 = /* transformMatrix */Layer$Gayer.defaultLayer[/* transformMatrix */4];

var midiColors_005 = /* filters */Layer$Gayer.defaultLayer[/* filters */5];

var midiColors = /* record */[
  midiColors_000,
  midiColors_001,
  /* compositeOperation : Multiply */11,
  midiColors_003,
  midiColors_004,
  midiColors_005
];

var midi_000 = history_000;

var midi_001 = history_001;

var midi_004 = history_004;

var midi_005 = history_005;

var midi_006 = history_006;

var midi_007 = history_007;

var midi_008 = history_008;

var midi_009 = history_009;

var midi_010 = history_010;

var midi_011 = history_011;

var midi_012 = history_012;

var midi_014 = /* layers : :: */[
  midiKeyboard,
  /* :: */[
    historyLayer,
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var midi = /* record */[
  midi_000,
  midi_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  midi_004,
  midi_005,
  midi_006,
  midi_007,
  midi_008,
  midi_009,
  midi_010,
  midi_011,
  midi_012,
  /* shouldClear */false,
  midi_014
];

var midiDroste_000 = droste_000;

var midiDroste_001 = droste_001;

var midiDroste_004 = droste_004;

var midiDroste_005 = droste_005;

var midiDroste_006 = droste_006;

var midiDroste_007 = droste_007;

var midiDroste_008 = droste_008;

var midiDroste_009 = droste_009;

var midiDroste_010 = droste_010;

var midiDroste_011 = droste_011;

var midiDroste_012 = droste_012;

var midiDroste_014 = /* layers : :: */[
  midiKeyboard,
  /* :: */[
    drosteLayer,
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var midiDroste = /* record */[
  midiDroste_000,
  midiDroste_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  midiDroste_004,
  midiDroste_005,
  midiDroste_006,
  midiDroste_007,
  midiDroste_008,
  midiDroste_009,
  midiDroste_010,
  midiDroste_011,
  midiDroste_012,
  /* shouldClear */false,
  midiDroste_014
];

var readFromCenterLine_000 = history_000;

var readFromCenterLine_001 = history_001;

var readFromCenterLine_004 = /* readPosOffset */Canvas$Gayer.defaultSize / 2 | 0;

var readFromCenterLine_005 = /* writePosOffset */Canvas$Gayer.defaultSize / 2 | 0;

var readFromCenterLine_006 = history_006;

var readFromCenterLine_007 = history_007;

var readFromCenterLine_008 = history_008;

var readFromCenterLine_009 = history_009;

var readFromCenterLine_010 = history_010;

var readFromCenterLine_011 = history_011;

var readFromCenterLine_012 = history_012;

var readFromCenterLine_014 = history_014;

var readFromCenterLine = /* record */[
  readFromCenterLine_000,
  readFromCenterLine_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  readFromCenterLine_004,
  readFromCenterLine_005,
  readFromCenterLine_006,
  readFromCenterLine_007,
  readFromCenterLine_008,
  readFromCenterLine_009,
  readFromCenterLine_010,
  readFromCenterLine_011,
  readFromCenterLine_012,
  /* shouldClear */false,
  readFromCenterLine_014
];

var historyBackAndForth_000 = readFromCenterLine_000;

var historyBackAndForth_001 = readFromCenterLine_001;

var historyBackAndForth_004 = readFromCenterLine_004;

var historyBackAndForth_005 = readFromCenterLine_005;

var historyBackAndForth_006 = readFromCenterLine_006;

var historyBackAndForth_007 = readFromCenterLine_007;

var historyBackAndForth_008 = readFromCenterLine_008;

var historyBackAndForth_009 = readFromCenterLine_009;

var historyBackAndForth_010 = readFromCenterLine_010;

var historyBackAndForth_011 = readFromCenterLine_011;

var historyBackAndForth_012 = readFromCenterLine_012;

var historyBackAndForth_014 = /* layers : :: */[
  analyzer,
  /* :: */[
    historyBackAndForthLayer,
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var historyBackAndForth = /* record */[
  historyBackAndForth_000,
  historyBackAndForth_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  historyBackAndForth_004,
  historyBackAndForth_005,
  historyBackAndForth_006,
  historyBackAndForth_007,
  historyBackAndForth_008,
  historyBackAndForth_009,
  historyBackAndForth_010,
  historyBackAndForth_011,
  historyBackAndForth_012,
  /* shouldClear */false,
  historyBackAndForth_014
];

var vinyl_000 = readFromCenterLine_000;

var vinyl_001 = readFromCenterLine_001;

var vinyl_004 = readFromCenterLine_004;

var vinyl_005 = readFromCenterLine_005;

var vinyl_006 = readFromCenterLine_006;

var vinyl_007 = readFromCenterLine_007;

var vinyl_008 = readFromCenterLine_008;

var vinyl_009 = readFromCenterLine_009;

var vinyl_010 = readFromCenterLine_010;

var vinyl_011 = readFromCenterLine_011;

var vinyl_012 = readFromCenterLine_012;

var vinyl_014 = /* layers : :: */[
  rotateLayer,
  /* :: */[
    analyzer,
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var vinyl = /* record */[
  vinyl_000,
  vinyl_001,
  /* readPosDelta */0,
  /* writePosDelta */0,
  vinyl_004,
  vinyl_005,
  vinyl_006,
  vinyl_007,
  vinyl_008,
  vinyl_009,
  vinyl_010,
  vinyl_011,
  vinyl_012,
  /* shouldClear */false,
  vinyl_014
];

var videoURL = "media/nonfree/kishi_bashi-say_yeah.mp4";

var video_000 = /* width */Params$Gayer.defaultParams[/* width */0];

var video_001 = /* height */Params$Gayer.defaultParams[/* height */1];

var video_002 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2];

var video_003 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3];

var video_004 = /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4];

var video_005 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5];

var video_006 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6];

var video_007 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7];

var video_008 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */8];

var video_009 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */9];

var video_010 = /* q */Params$Gayer.defaultParams[/* q */10];

var video_011 = /* transpose */Params$Gayer.defaultParams[/* transpose */11];

var video_012 = /* stereo */Params$Gayer.defaultParams[/* stereo */12];

var video_013 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13];

var video_014 = /* layers : :: */[
  video(videoURL),
  /* :: */[
    /* record */[
      /* content : Analysis */Block.__(5, [/* AudioFromVideo */Block.__(1, [videoURL])]),
      analyzer_001,
      analyzer_002,
      analyzer_003,
      analyzer_004,
      analyzer_005
    ],
    /* :: */[
      reader,
      /* [] */0
    ]
  ]
];

var video$1 = /* record */[
  video_000,
  video_001,
  video_002,
  video_003,
  video_004,
  video_005,
  video_006,
  video_007,
  video_008,
  video_009,
  video_010,
  video_011,
  video_012,
  video_013,
  video_014
];

var presets_000 = /* tuple */[
  "Spacy",
  /* record */[
    /* width */Params$Gayer.defaultParams[/* width */0],
    /* height */Params$Gayer.defaultParams[/* height */1],
    /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2],
    /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3],
    /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4],
    /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5],
    /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6],
    /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7],
    /* inputGain */Params$Gayer.defaultParams[/* inputGain */8],
    /* outputGain */Params$Gayer.defaultParams[/* outputGain */9],
    /* q */Params$Gayer.defaultParams[/* q */10],
    /* transpose */Params$Gayer.defaultParams[/* transpose */11],
    /* stereo */Params$Gayer.defaultParams[/* stereo */12],
    /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13],
    /* layers */spacy
  ]
];

var presets_001 = /* :: */[
  /* tuple */[
    "Single note",
    singleNote
  ],
  /* :: */[
    /* tuple */[
      "Slitscan",
      slitscanParams
    ],
    /* :: */[
      /* tuple */[
        "History",
        history
      ],
      /* :: */[
        /* tuple */[
          "Rotation",
          vinyl
        ],
        /* :: */[
          /* tuple */[
            "Tughra of Suleiman",
            tughra
          ],
          /* :: */[
            /* tuple */[
              "Is it a crime?",
              isItACrime
            ],
            /* :: */[
              /* tuple */[
                "MIDI",
                midi
              ],
              /* :: */[
                /* tuple */[
                  "Mic feedback (may be loud!)",
                  feedback
                ],
                /* :: */[
                  /* tuple */[
                    "Empty",
                    /* record */[
                      /* width */Params$Gayer.defaultParams[/* width */0],
                      /* height */Params$Gayer.defaultParams[/* height */1],
                      /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */2],
                      /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */3],
                      /* readPosOffset */Params$Gayer.defaultParams[/* readPosOffset */4],
                      /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */5],
                      /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */6],
                      /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */7],
                      /* inputGain */Params$Gayer.defaultParams[/* inputGain */8],
                      /* outputGain */Params$Gayer.defaultParams[/* outputGain */9],
                      /* q */Params$Gayer.defaultParams[/* q */10],
                      /* transpose */Params$Gayer.defaultParams[/* transpose */11],
                      /* stereo */Params$Gayer.defaultParams[/* stereo */12],
                      /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */13],
                      /* layers : [] */0
                    ]
                  ],
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var presets = /* :: */[
  presets_000,
  presets_001
];

var defaultSize = Canvas$Gayer.defaultSize;

var defaultTransform = Canvas$Gayer.defaultTransform;

var tau = Canvas$Gayer.tau;

export {
  defaultSize ,
  defaultTransform ,
  tau ,
  img ,
  reader ,
  pitchFilter ,
  fill ,
  draw ,
  analyzer ,
  webcam ,
  slitscan ,
  hubble ,
  spacy ,
  drawSelfFullScreen ,
  harmony ,
  rotateLayer ,
  blurLayer ,
  squareColumnLayer ,
  squareLayer ,
  singleNoteDrawCommands ,
  singleNoteLayer ,
  singleNote ,
  historyLayer ,
  historyBackAndForthLayer ,
  drosteLayer ,
  allLayerTypes ,
  harmonyParams ,
  harmonyIntensified ,
  feedback ,
  slitscanParams ,
  whiteboardParams ,
  isItACrime ,
  tughra ,
  iChing ,
  history ,
  historyHalving ,
  debussyFile ,
  debussy ,
  droste ,
  midiKeyboard ,
  midiColors ,
  midi ,
  midiDroste ,
  readFromCenterLine ,
  historyBackAndForth ,
  vinyl ,
  videoURL ,
  video$1 as video,
  presets ,
  
}
/* hubble Not a pure module */
