// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Music$Gayer from "./Music.bs.js";
import * as Canvas$Gayer from "./Canvas.bs.js";
import * as Params$Gayer from "./Params.bs.js";

var baseLayer_000 = /* content : Fill */Block.__(0, ["black"]);

var baseLayer = /* record */[
  baseLayer_000,
  /* alpha */1.0,
  /* compositeOperation : SourceOver */0,
  /* transformMatrix */Canvas$Gayer.defaultTransform
];

var analyzer_000 = /* content : Analysis */Block.__(3, [/* Mic */1]);

var analyzer = /* record */[
  analyzer_000,
  /* alpha */1.0,
  /* compositeOperation : SourceOver */0,
  /* transformMatrix */Canvas$Gayer.defaultTransform
];

var webcam_000 = /* content : Webcam */Block.__(1, [/* record */[/* slitscan */undefined]]);

var webcam = /* record */[
  webcam_000,
  /* alpha */1.0,
  /* compositeOperation : SourceOver */0,
  /* transformMatrix */Canvas$Gayer.defaultTransform
];

var slitscan_000 = /* content : Webcam */Block.__(1, [/* record */[/* slitscan *//* record */[/* x */320]]]);

var slitscan = /* record */[
  slitscan_000,
  /* alpha */1.0,
  /* compositeOperation : SourceOver */0,
  /* transformMatrix */Canvas$Gayer.defaultTransform
];

var reader_000 = /* content : Reader */Block.__(5, [/* R */0]);

var reader = /* record */[
  reader_000,
  /* alpha */0.1,
  /* compositeOperation : SourceOver */0,
  /* transformMatrix */Canvas$Gayer.defaultTransform
];

function pitchFilter(pc) {
  return /* record */[
          /* content : PitchClasses */Block.__(4, [pc]),
          /* alpha */1.0,
          /* compositeOperation : DestinationOut */6,
          /* transformMatrix */Canvas$Gayer.defaultTransform
        ];
}

function fill($staropt$star, fillStyle) {
  var alpha = $staropt$star !== undefined ? $staropt$star : 1.0;
  return /* record */[
          /* content : Fill */Block.__(0, [fillStyle]),
          /* alpha */alpha,
          /* compositeOperation : SourceOver */0,
          /* transformMatrix */Canvas$Gayer.defaultTransform
        ];
}

function img(url) {
  return /* record */[
          /* content : Image */Block.__(2, [url]),
          /* alpha */1.0,
          /* compositeOperation : SourceOver */0,
          /* transformMatrix */Canvas$Gayer.defaultTransform
        ];
}

var hubble = img("media/hubble_ultra_deep_field.jpg");

var spacy_001 = /* :: */[
  pitchFilter(Music$Gayer.cMajor),
  /* :: */[
    reader,
    /* [] */0
  ]
];

var spacy = /* :: */[
  hubble,
  spacy_001
];

var init = img("media/harmony.png");

var harmony_000 = fill(0.1, "black");

var harmony_001 = /* :: */[
  /* record */[
    /* content */init[/* content */0],
    /* alpha */init[/* alpha */1],
    /* compositeOperation */init[/* compositeOperation */2],
    /* transformMatrix : record */[
      /* horizontalScaling */Canvas$Gayer.defaultTransform[/* horizontalScaling */0],
      /* horizontalSkewing */Canvas$Gayer.defaultTransform[/* horizontalSkewing */1],
      /* verticalSkewing */Canvas$Gayer.defaultTransform[/* verticalSkewing */2],
      /* verticalScaling */Canvas$Gayer.defaultTransform[/* verticalScaling */3],
      /* horizontalMoving */Canvas$Gayer.defaultTransform[/* horizontalMoving */4],
      /* verticalMoving */48.0
    ]
  ],
  /* :: */[
    /* record */[
      /* content : Analysis */Block.__(3, [/* Mic */1]),
      /* alpha */0.25,
      /* compositeOperation : Overlay */13,
      /* transformMatrix */Canvas$Gayer.defaultTransform
    ],
    /* :: */[
      /* record */[
        /* content : Webcam */Block.__(1, [/* record */[/* slitscan */undefined]]),
        /* alpha */0.25,
        /* compositeOperation : Overlay */13,
        /* transformMatrix */Canvas$Gayer.defaultTransform
      ],
      /* :: */[
        pitchFilter(Music$Gayer.cMajor),
        /* :: */[
          /* record */[
            /* content : Reader */Block.__(5, [/* R */0]),
            /* alpha */0.0,
            /* compositeOperation : SourceOver */0,
            /* transformMatrix */Canvas$Gayer.defaultTransform
          ],
          /* [] */0
        ]
      ]
    ]
  ]
];

var harmony = /* :: */[
  harmony_000,
  harmony_001
];

var allLayerTypes_001 = /* :: */[
  analyzer,
  /* :: */[
    webcam,
    /* :: */[
      slitscan,
      /* :: */[
        fill(0.0125, "white"),
        /* :: */[
          pitchFilter(Music$Gayer.cMajor),
          /* :: */[
            reader,
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

var allLayerTypes = /* :: */[
  hubble,
  allLayerTypes_001
];

var harmonyParams_000 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */0];

var harmonyParams_001 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */1];

var harmonyParams_002 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */2];

var harmonyParams_004 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */4];

var harmonyParams_005 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */5];

var harmonyParams_006 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */6];

var harmonyParams_007 = /* q */Params$Gayer.defaultParams[/* q */7];

var harmonyParams_008 = /* transpose */Params$Gayer.defaultParams[/* transpose */8];

var harmonyParams = /* record */[
  harmonyParams_000,
  harmonyParams_001,
  harmonyParams_002,
  /* millisPerTick */25,
  harmonyParams_004,
  harmonyParams_005,
  harmonyParams_006,
  harmonyParams_007,
  harmonyParams_008,
  /* shouldClear */false,
  /* layers */harmony
];

var harmonyIntensified_000 = harmonyParams_000;

var harmonyIntensified_001 = harmonyParams_001;

var harmonyIntensified_002 = harmonyParams_002;

var harmonyIntensified_004 = harmonyParams_004;

var harmonyIntensified_005 = harmonyParams_005;

var harmonyIntensified_006 = harmonyParams_006;

var harmonyIntensified_007 = harmonyParams_007;

var harmonyIntensified_008 = harmonyParams_008;

var harmonyIntensified_010 = /* layers : :: */[
  img("media/harmony_intensified.png"),
  /* :: */[
    reader,
    /* [] */0
  ]
];

var harmonyIntensified = /* record */[
  harmonyIntensified_000,
  harmonyIntensified_001,
  harmonyIntensified_002,
  /* millisPerTick */25,
  harmonyIntensified_004,
  harmonyIntensified_005,
  harmonyIntensified_006,
  harmonyIntensified_007,
  harmonyIntensified_008,
  /* shouldClear */false,
  harmonyIntensified_010
];

var feedback_000 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */0];

var feedback_001 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */1];

var feedback_002 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */2];

var feedback_003 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */3];

var feedback_005 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */5];

var feedback_006 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */6];

var feedback_007 = /* q */Params$Gayer.defaultParams[/* q */7];

var feedback_008 = /* transpose */Params$Gayer.defaultParams[/* transpose */8];

var feedback_009 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */9];

var feedback_010 = /* layers : :: */[
  webcam,
  /* :: */[
    /* record */[
      /* content : Analysis */Block.__(3, [/* Mic */1]),
      /* alpha */0.5,
      /* compositeOperation : SourceOver */0,
      /* transformMatrix */Canvas$Gayer.defaultTransform
    ],
    /* :: */[
      pitchFilter(Music$Gayer.cMajor),
      /* :: */[
        reader,
        /* [] */0
      ]
    ]
  ]
];

var feedback = /* record */[
  feedback_000,
  feedback_001,
  feedback_002,
  feedback_003,
  /* audioInputSetting : Mic */1,
  feedback_005,
  feedback_006,
  feedback_007,
  feedback_008,
  feedback_009,
  feedback_010
];

var slitscanParams_000 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */0];

var slitscanParams_001 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */1];

var slitscanParams_002 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */2];

var slitscanParams_003 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */3];

var slitscanParams_004 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */4];

var slitscanParams_005 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */5];

var slitscanParams_006 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */6];

var slitscanParams_007 = /* q */Params$Gayer.defaultParams[/* q */7];

var slitscanParams_008 = /* transpose */Params$Gayer.defaultParams[/* transpose */8];

var slitscanParams_010 = /* layers : :: */[
  slitscan,
  /* :: */[
    /* record */[
      /* content : Analysis */Block.__(3, [/* Mic */1]),
      /* alpha */0.25,
      /* compositeOperation : SourceOver */0,
      /* transformMatrix */Canvas$Gayer.defaultTransform
    ],
    /* :: */[
      pitchFilter(Music$Gayer.cMajor),
      /* :: */[
        reader,
        /* [] */0
      ]
    ]
  ]
];

var slitscanParams = /* record */[
  slitscanParams_000,
  slitscanParams_001,
  slitscanParams_002,
  slitscanParams_003,
  slitscanParams_004,
  slitscanParams_005,
  slitscanParams_006,
  slitscanParams_007,
  slitscanParams_008,
  /* shouldClear */false,
  slitscanParams_010
];

var isItACrime_000 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */0];

var isItACrime_001 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */1];

var isItACrime_002 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */2];

var isItACrime_004 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */4];

var isItACrime_005 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */5];

var isItACrime_007 = /* q */Params$Gayer.defaultParams[/* q */7];

var isItACrime_008 = /* transpose */Params$Gayer.defaultParams[/* transpose */8];

var isItACrime_009 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */9];

var isItACrime_010 = /* layers : :: */[
  img("media/is_it_a_crime.png"),
  /* :: */[
    /* record */[
      /* content : Reader */Block.__(5, [/* A */3]),
      /* alpha */0.1,
      /* compositeOperation : SourceOver */0,
      /* transformMatrix */Canvas$Gayer.defaultTransform
    ],
    /* [] */0
  ]
];

var isItACrime = /* record */[
  isItACrime_000,
  isItACrime_001,
  isItACrime_002,
  /* millisPerTick */33,
  isItACrime_004,
  isItACrime_005,
  /* outputGain */0.2,
  isItACrime_007,
  isItACrime_008,
  isItACrime_009,
  isItACrime_010
];

var tughra_000 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */0];

var tughra_001 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */1];

var tughra_002 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */2];

var tughra_004 = /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */4];

var tughra_005 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */5];

var tughra_006 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */6];

var tughra_007 = /* q */Params$Gayer.defaultParams[/* q */7];

var tughra_008 = /* transpose */Params$Gayer.defaultParams[/* transpose */8];

var tughra_009 = /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */9];

var tughra_010 = /* layers : :: */[
  img("media/suleiman.jpg"),
  /* :: */[
    /* record */[
      /* content : Reader */Block.__(5, [/* R */0]),
      /* alpha */0.25,
      /* compositeOperation : SourceOver */0,
      /* transformMatrix */Canvas$Gayer.defaultTransform
    ],
    /* [] */0
  ]
];

var tughra = /* record */[
  tughra_000,
  tughra_001,
  tughra_002,
  /* millisPerTick */33,
  tughra_004,
  tughra_005,
  tughra_006,
  tughra_007,
  tughra_008,
  tughra_009,
  tughra_010
];

var debussyFile_000 = /* content : Analysis */Block.__(3, [/* AudioFile */["media/la_cathedrale_engloutie.m4a"]]);

var debussyFile = /* record */[
  debussyFile_000,
  /* alpha */1.0,
  /* compositeOperation : SourceOver */0,
  /* transformMatrix */Canvas$Gayer.defaultTransform
];

var debussy_000 = /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */0];

var debussy_001 = /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */1];

var debussy_002 = /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */2];

var debussy_003 = /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */3];

var debussy_005 = /* inputGain */Params$Gayer.defaultParams[/* inputGain */5];

var debussy_006 = /* outputGain */Params$Gayer.defaultParams[/* outputGain */6];

var debussy_007 = /* q */Params$Gayer.defaultParams[/* q */7];

var debussy_008 = /* transpose */Params$Gayer.defaultParams[/* transpose */8];

var debussy_010 = /* layers : :: */[
  debussyFile,
  /* :: */[
    reader,
    /* [] */0
  ]
];

var debussy = /* record */[
  debussy_000,
  debussy_001,
  debussy_002,
  debussy_003,
  /* audioInputSetting : PinkNoise */0,
  debussy_005,
  debussy_006,
  debussy_007,
  debussy_008,
  /* shouldClear */false,
  debussy_010
];

var presets_000 = /* tuple */[
  "Spacy",
  /* record */[
    /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */0],
    /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */1],
    /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */2],
    /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */3],
    /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */4],
    /* inputGain */Params$Gayer.defaultParams[/* inputGain */5],
    /* outputGain */Params$Gayer.defaultParams[/* outputGain */6],
    /* q */Params$Gayer.defaultParams[/* q */7],
    /* transpose */Params$Gayer.defaultParams[/* transpose */8],
    /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */9],
    /* layers */spacy
  ]
];

var presets_001 = /* :: */[
  /* tuple */[
    "Harmony",
    harmonyParams
  ],
  /* :: */[
    /* tuple */[
      "Tughra of Suleiman",
      tughra
    ],
    /* :: */[
      /* tuple */[
        "Is it a crime?",
        isItACrime
      ],
      /* :: */[
        /* tuple */[
          "Slitscan",
          slitscanParams
        ],
        /* :: */[
          /* tuple */[
            "Debussy",
            debussy
          ],
          /* :: */[
            /* tuple */[
              "Mic feedback (may be loud!)",
              feedback
            ],
            /* :: */[
              /* tuple */[
                "Empty",
                /* record */[
                  /* readPosDelta */Params$Gayer.defaultParams[/* readPosDelta */0],
                  /* writePosDelta */Params$Gayer.defaultParams[/* writePosDelta */1],
                  /* writePosOffset */Params$Gayer.defaultParams[/* writePosOffset */2],
                  /* millisPerTick */Params$Gayer.defaultParams[/* millisPerTick */3],
                  /* audioInputSetting */Params$Gayer.defaultParams[/* audioInputSetting */4],
                  /* inputGain */Params$Gayer.defaultParams[/* inputGain */5],
                  /* outputGain */Params$Gayer.defaultParams[/* outputGain */6],
                  /* q */Params$Gayer.defaultParams[/* q */7],
                  /* transpose */Params$Gayer.defaultParams[/* transpose */8],
                  /* shouldClear */Params$Gayer.defaultParams[/* shouldClear */9],
                  /* layers : [] */0
                ]
              ],
              /* [] */0
            ]
          ]
        ]
      ]
    ]
  ]
];

var presets = /* :: */[
  presets_000,
  presets_001
];

var defaultTransform = Canvas$Gayer.defaultTransform;

export {
  defaultTransform ,
  baseLayer ,
  analyzer ,
  webcam ,
  slitscan ,
  reader ,
  pitchFilter ,
  fill ,
  img ,
  hubble ,
  spacy ,
  harmony ,
  allLayerTypes ,
  harmonyParams ,
  harmonyIntensified ,
  feedback ,
  slitscanParams ,
  isItACrime ,
  tughra ,
  debussyFile ,
  debussy ,
  presets ,
  
}
/* hubble Not a pure module */
