// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";
import * as Params$Gayer from "./Params.bs.js";

function pushParamsState($staropt$star, newParams) {
  var maybeI = $staropt$star !== undefined ? Js_primitive.valFromOption($staropt$star) : undefined;
  var newParamsJson = encodeURIComponent(JSON.stringify(Params$Gayer.EncodeParams[/* params */0](newParams)));
  var maybeScoreIndex = maybeI !== undefined ? "?" + String(maybeI) : "";
  return ReasonReact.Router[/* push */0](maybeScoreIndex + ("#" + newParamsJson));
}

export {
  pushParamsState ,
  
}
/* ReasonReact Not a pure module */
