// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as UserMedia$Gayer from "./UserMedia.bs.js";

var attachVideoStream = function (stream){
  var video = document.getElementsByTagName("video")[0];
  video.srcObject = stream;
  return video;
};

function turnOnVideo() {
  var match = UserMedia$Gayer.getVideoStream(/* () */0);
  if (match) {
    return match[0].then((function (stream) {
                  return Promise.resolve(/* Some */[attachVideoStream(stream)]);
                }));
  } else {
    return Promise.resolve(/* None */0);
  }
}

export {
  attachVideoStream ,
  turnOnVideo ,
  
}
/* No side effect */
