// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE


var attachVideoStream = function (video,stream){
  video.srcObject = stream;
  return video;
};

export {
  attachVideoStream ,
  
}
/* No side effect */
