// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as Color$Gayer from "../src/Color.bs.js";

describe("rgbToHsvFloat", (function () {
        Jest.test("converts red to hue == 0", (function () {
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            0.0,
                            1.0,
                            1.0
                          ], Jest.Expect[/* expect */0](Color$Gayer.rgbToHsvFloat(1.0, 0.0, 0.0)));
              }));
        Jest.test("converts green to hue == 1/3", (function () {
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            1.0 / 3.0,
                            1.0,
                            1.0
                          ], Jest.Expect[/* expect */0](Color$Gayer.rgbToHsvFloat(0.0, 1.0, 0.0)));
              }));
        return Jest.test("converts blue to hue == 2/3", (function () {
                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                  2.0 / 3.0,
                                  1.0,
                                  1.0
                                ], Jest.Expect[/* expect */0](Color$Gayer.rgbToHsvFloat(0.0, 0.0, 1.0)));
                    }));
      }));

export {
  
}
/*  Not a pure module */
