// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/lib/es6/src/jest.js";
import * as Params$Gayer from "../src/Params.bs.js";

describe("EncodeParams <=> DecodeParams", (function () {
        return Jest.test("decode inverts encode", (function () {
                      return Jest.Expect[/* toBe */2](Params$Gayer.defaultParams, Jest.Expect[/* expect */0](Params$Gayer.DecodeParams[/* params */0](Params$Gayer.EncodeParams[/* params */0](Params$Gayer.defaultParams))));
                    }));
      }));

export {
  
}
/*  Not a pure module */
